### ISSUE TITLE
Add Feature to "Publish" Collections

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1482]
Add a "Publish" button to Collections/EPICollections edit forms, display only if user is authed as "Data Admin" and a DOI does not exist for the Collection.  This should call ingest-api `PUT /collections/<id>/register-doi`, on a non-200 result display error information.

**Comment by BirdMachine** [comment]
```[tasklist]
### Tasks
- [ ] Add button to "Publish" Collections
- [ ] Configure and Validate Specific Hide/Show/Permission Logic 
- [ ] Add the register-doi endpoint to Entity services 
```
