### ISSUE TITLE
Workflow of derived dataset with Airflow

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/ingest-ui#80]
This is the Epic issue of the related workflow, please add/link the items to their own issues once they are created in the proper repo:

- [ ] Ingest UI receives new data set (for development, this is copied to a new test directory)
- [ ] Ingest UI calls Joel's metadata extraction Airflow DAG
- [ ] Metadata extraction DAG runs
- [ ] Metadata extraction DAG sends metadata back to Ingest UI
- [ ] Ingest UI updates object with metadata provided by the DAG and sets the object state (Error, QA, etc.)
- [ ] Enhanced metadata extraction DAG (or a new DAG) runs Matt's RNA-Seq pipeline on the uploaded data set. Intermediate files are stored in a tmp space, e.g., /hive/hubmap/tmp
- [ ] Once the pipeline is complete, the DAG calls the POST API that Joe is going to write to register a new data set, get a UUID, create a new UUID directory for the data set, etc.
- [ ] Once the new UUID directory is set, DAG copies derived data to permanent UUID directory. 
- [ ] DAG calls Ingest UI API used to update original data object with metadata about the new derived data object.

**Comment by yuanzhou** [comment]
Added the API endpoint and functionalities via pull request #82
